# Copyright by Shlomi Fish, 2018 under the Expat licence
# https://opensource.org/licenses/mit-license.php

all:

upload:
	rsync -a -v --progress --inplace ./html-analysis.html $$__HOMEPAGE_REMOTE_PATH/Files/files/text/
